### ISSUE TITLE
CSR display issue: spaces before CSR

### ISSUE THREAD

**Issue by markholland83** [realtimeregister/whmcs-ssl-addon#42]
There are loads of spacing before the Certificate Signing Request on the productdetails page.

![Image](https://github.com/user-attachments/assets/49c5cab2-23ee-49b0-8702-ad362c85f0ec)

**Comment by PJEilers** [comment]
Fixed in new version:

https://github.com/realtimeregister/whmcs-ssl-addon/releases/tag/v0.4.11-beta

**Comment by MarkKraakman** [comment]
The issue still exists on the configuration step 1 page:

![Image](https://github.com/user-attachments/assets/277c5f1a-f92c-4614-8a94-a57760fe9d2f)
